export { HomePage } from './Home.page';
export { ProjectList } from './ProjectList.page';
export { DetailPage } from './Detail.page';
export { ContractPage } from './Contract.page';
export { ContractManage } from './ContractManage.page';
export { ChattingPage } from './Chatting.page';
export { AdminChatPage } from './AdminChat.page';
export { CardManage } from './CardManage.page';
export { Profile } from './Profile.page';
export { Payment } from './Payment.page'
export { Admin } from './Admin.page';
